### ISSUE TITLE
Cant Dupe EA2 chips

### ISSUE THREAD

**Issue by vekenti** [Rusketh/ExpAdv2#174] opened 2015-02-01 16:15 UTC
Cant dupe EA2 chips on multiple servers

**Comment by AdamName** [comment] 2015-02-01 19:19
Have you tried turning your computer off and on again?

**Comment by Ripmax** [comment] 2015-02-01 19:20
What do you mean by multiple servers, do you mean the issue is happening on only some servers or... what?

**Comment by thegrb93** [comment] 2015-02-01 19:58
Conflicting versions maybe.

**Comment by AdamName** [comment] 2015-02-01 20:48
Expression Advanced 2 IT Specialist talking. Have you tried turning your computer off and on again?

**Comment by Damianu** [comment] 2015-02-01 22:21
I will do
[Stupid post]

**Comment by AdamName** [comment] 2015-02-01 22:24
Expression Advanced 2 IT Specialist talking. Have you tried turning it off and on again?

**Comment by Rusketh** [comment] 2015-02-03 11:02
I am closing this issue, You need to put more then 'can't dupe ea2 chips'.

**Closed by Rusketh** 2015-02-03 11:02 UTC
